---
transformations:
  - id: '0'
    matrix:
      - [0.866, -0.5, 0.0, 1.0]
      - [0.5, 0.866, 0.0, 2.0]
      - [0.0, 0.0, 1.0, 3.0]
      - [0.0, 0.0, 0.0, 1.0]
  - id: '1'
    matrix:
      - [1.0, 0.0, 0.0, 0.0]
      - [0.0, 1.0, 0.0, 0.0]
      - [0.0, 0.0, 1.0, 0.0]
      - [0.0, 0.0, 0.0, 1.0]